# Generated by Django 5.2.6 on 2025-09-12 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('property_address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('site_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('schema_version', models.IntegerField()),
                ('site_key', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('page_load', 'Page Load'), ('form_submission', 'Form Submission'), ('custom_event', 'Custom Event')], db_index=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('page_title', models.CharField(blank=True, max_length=512, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('language', models.CharField(blank=True, max_length=32, null=True)),
                ('tz_offset_min', models.IntegerField(blank=True, null=True)),
                ('viewport', models.JSONField(blank=True, null=True)),
                ('screen', models.JSONField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.lead')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.session')),
            ],
            options={
                'indexes': [models.Index(fields=['site_key', 'created_at'], name='tracker_eve_site_ke_70de0e_idx'), models.Index(fields=['session', 'created_at'], name='tracker_eve_session_f2c059_idx')],
            },
        ),
    ]
