# Generated by Django 5.2.6 on 2025-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='created_at',
            new_name='first_seen',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='updated_at',
            new_name='last_seen',
        ),
        migrations.AddField(
            model_name='session',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
